"""add_draft_data_and_nullable_name_email

Revision ID: 4e095a74225a
Revises: 1565b12ac084
Create Date: 2026-06-01 23:25:35.261564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e095a74225a'
down_revision: Union[str, Sequence[str], None] = '1565b12ac084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('draft_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('user_profiles', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user_profiles', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_profiles', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user_profiles', 'draft_data')
    # ### end Alembic commands ###
