"""add projects, certifications, profile link columns

Revision ID: bbb5e25639d6
Revises: 4e095a74225a
Create Date: 2026-06-02 23:17:54.615522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbb5e25639d6'
down_revision: Union[str, Sequence[str], None] = '4e095a74225a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bullets', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('tech_stack', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_profiles', sa.Column('github_url', sa.String(length=500), nullable=True))
    op.add_column('user_profiles', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('user_profiles', sa.Column('portfolio_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'portfolio_url')
    op.drop_column('user_profiles', 'linkedin_url')
    op.drop_column('user_profiles', 'github_url')
    op.drop_table('projects')
    op.drop_table('certifications')
    # ### end Alembic commands ###
