"""add locations, education dates, skill category, languages

Revision ID: c6856a75cd09
Revises: bbb5e25639d6
Create Date: 2026-06-03 00:42:41.292861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6856a75cd09'
down_revision: Union[str, Sequence[str], None] = 'bbb5e25639d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('educations', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('educations', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('educations', sa.Column('end_date', sa.Date(), nullable=True))
    op.drop_column('educations', 'year')
    op.add_column('experiences', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('skills', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'category')
    op.drop_column('experiences', 'location')
    op.add_column('educations', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('educations', 'end_date')
    op.drop_column('educations', 'start_date')
    op.drop_column('educations', 'location')
    op.drop_table('languages')
    # ### end Alembic commands ###
